Brother\QuestBundle\Entity\Quest:
    type: entity
    repositoryClass: Brother\QuestBundle\Repository\QuestRepository
    gedmo:
        soft_deleteable:
            field_name: deleted_at
            time_aware: false
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 100
            nullable: false
        q:
            type: string
            length: 255
        a:
            type: string
            length: 255
        email:
            type: string
            length: 255
        executor:
            type: string
            length: 255
        comment:
            type: string
            length: 255
        priority:
            type: string
            length: 255
        created_by:
            type: integer
            nullable: true
        updated_by: 
            type: integer
            nullable: true
        created_at:
            type: datetime
            nullable: true
        updated_at:
            type: datetime
            nullable: true
        deleted_at:
            type: datetime
            nullable: true
        status:
            type: string
            length: 255
            nullable: true
    lifecycleCallbacks: 
        prePersist: prePersist
        preUpdate: preUpdate
