services:
    brother_quest.form.entry.type:
        class: %brother_quest.form.entry.class%
        tags:
            - { name: form.type, alias: brother_quest_entry }
        arguments:
            - %brother_quest.model.entry.class%

    brother_quest.form_factory.entry:
        factory: ['@form.factory', 'createNamed']
        class: Symfony\Component\Form\Form
        arguments:
            - %brother_quest.form.entry.name%
            - %brother_quest.form.entry.type%
            - ~


