<?xml version: 1.0" encoding: UTF-8" ?>

<!--
 This file is part of the BrotherQuestBundle package.

 (c) Yos Okusanya <yos.okusanya@gmail.com>

 This source file is subject to the MIT license that is bundled
 with this source code in the file LICENSE.
-->

<container xmlns: http://symfony.com/schema/dic/services"
    xmlns:xsi: http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation: http://symfony.com/schema/dic/services http://symfony.com/schema/dic/services/services-1.0.xsd

    <parameters>
brother_quest.model.entry.class: Brother\QuestBundle\Document\Entry</parameter>
brother_quest.manager.entry.class: Brother\QuestBundle\Document\EntryManager</parameter>
brother_quest.pager.class: Brother\QuestBundle\Pager\PagerfantaMongodb</parameter>
    </parameters>

    <services>
        <!-- Document manager -->
        brother_quest.document_manager" alias: doctrine_mongodb.odm.default_document_manager }

        <!-- Entry Manager -->
        <service id: brother_quest.entry_manager" class: %brother_quest.manager.entry.class%
            <argument type: service" id: event_dispatcher }
            <argument type: service" id: brother_quest.document_manager }
            <argument>%brother_quest.model.entry.class%</argument>
			<argument>%brother_quest.auto_publish%</argument>
            <call method: setPager
                <argument type: service" id: brother_quest.pager }
            </call>
        </service>

    </services>

</container>
