parameters:
    brother_quest.model.entry.class: Brother\QuestBundle\Entity\Entry
    brother_quest.manager.entry.class: Brother\QuestBundle\Entity\EntryManager
    brother_quest.pager.class: Brother\QuestBundle\Pager\PagerfantaORM
services:
    brother_quest.entity_manager:
        alias: 'doctrine.orm.entity_manager'
    brother_quest.entry_manager:
        class: %brother_quest.manager.entry.class%
        arguments:
            - '@event_dispatcher'
            - '@brother_quest.entity_manager'
            - %brother_quest.model.entry.class%
            - %brother_quest.auto_publish%
        calls:
            - [setPager, ['@brother_quest.pager']]
