services:
    brother_quest.admin.quest:
        class: Brother\QuestBundle\Admin\QuestAdmin
        arguments: [~, Brother\QuestBundle\Entity\Quest, BrotherQuestBundle:QuestAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Quest}
