parameters:
    brother_quest.mailer.config:
        notification:
            title: %brother_quest.mailer.email_title%
            from: %brother_quest.mailer.sender_email%
            to: %brother_quest.mailer.admin_email%
            view: %brother_quest.view.mail.notify%
services:

    gedmo.listener.softdeleteable:
        class: Gedmo\SoftDeleteable\SoftDeleteableListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, [ @annotation_reader ] ]


    brother_quest.pager.default:
        class: %brother_quest.pager.class%
#        arguments:
#            - { type: service, id: twig.extension.pagerfanta, on-invalid: null}

    brother_quest.mailer:
        class: %brother_quest.mailer.class%
        arguments:
            - '@event_dispatcher'
            - { type: service', id: mailer, on-invalid: null}
            - '@templating'
            - %brother_quest.mailer.config%

    brother_quest.admin.entry:
        class: Brother\QuestBundle\Admin\EntryAdmin
        arguments: [~, Brother\QuestBundle\Entity\Entry, BrotherQuestBundle:EntryAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Quest}
