#
# This file is part of the BrotherQuestBundle package.
#
# (c) Yos Okusanya <yos.okusanya@gmail.com>
#
# This source file is subject to the MIT license that is bundled
# with this source code in the file LICENSE.

Brother\QuestBundle\Model\Entry:
    properties:
        name:
            - NotBlank:
                message: brother_quest.name.blank
            - Length:
                min: 3
                max: 100
                #max: 255
                minMessage: brother_quest.name.short
                maxMessage: brother_quest.name.long

        email:
            - NotBlank:
                message: brother_quest.email.blank
            - Email:
                message: brother_quest.email.invalid
            - Length:
                max: 100
                #max: 255
                minMessage: brother_quest.email.short
                maxMessage: brother_quest.email.long

        q:
            - NotBlank:
                message: brother_quest.q.blank
            - Length:
                min: 2
                #max: 255
                minMessage: brother_quest.q.short
                maxMessage: brother_quest.q.long
