brother_quest_list:
    path:     /{page}
    defaults: { _controller: "BrotherQuestBundle:Entry:index", page: 1 }
    requirements:
        page: \d+

brother_quest_new_dialog:
    path:     /new
    defaults: { _controller: "BrotherQuestBundle:Entry:newDialog" }

brother_quest_create_ajax:
    path:     /create
    defaults: { _controller: "BrotherQuestBundle:Entry:create" }
    methods: [POST]
