quest:
    path:     /
    defaults: { _controller: "BrotherQuestBundle:Quest:index" }

quest_show:
    path:     /{id}/show
    defaults: { _controller: "BrotherQuestBundle:Quest:show" }

quest_new:
    path:     /new
    defaults: { _controller: "BrotherQuestBundle:Quest:new" }

quest_create:
    path:     /create
    defaults: { _controller: "BrotherQuestBundle:Quest:create" }
    methods:  POST

quest_edit:
    path:     /{id}/edit
    defaults: { _controller: "BrotherQuestBundle:Quest:edit" }

quest_update:
    path:     /{id}/update
    defaults: { _controller: "BrotherQuestBundle:Quest:update" }
    methods:  [POST, PUT]

quest_delete:
    path:     /{id}/delete
    defaults: { _controller: "BrotherQuestBundle:Quest:delete" }
    methods:  [POST, DELETE]
